
FROM golang:1.20 as builder


WORKDIR /app


COPY . .


RUN go mod tidy


RUN go build -o auth-service main.go


FROM debian:bullseye-slim


WORKDIR /app


COPY --from=builder /app/auth-service .


EXPOSE 8080


CMD ["./auth-service"]